In [160]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import operator
%matplotlib inline

In [161]:
#load in the csv into pd structure
crimeData = pd.read_csv('crime_data.csv',header=0,index_col=0)
#drop any rows with a nan
crimeData.dropna(how='any',axis='rows')

,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated Assault,Burglary,Larceny,Vehicle Theft
Year,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
1966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
1967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
1968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
1969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
1970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
1971,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
1972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
1973,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
1974,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1976,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
1977,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
1978,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1979,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1980,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1981,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1982,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1984,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
1985,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
1986,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1987,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1988,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1989,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1990,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1991,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1992,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1993,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
1994,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1995,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
1996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
1997,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
1998,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
1999,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
2000,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
2001,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
2002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
2003,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
2004,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
2005,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
2006,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
2007,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
2008,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
2009,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
2010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
2011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014,318907401,9395195,1186185,8209010,14164,84864,322905,731089,1713153,5809054,686803
2015,320896618,9258298,1234183,8024115,15883,91261,328109,764057,1587564,5723488,713063
2016,323127513,9202093,1283058,7919035,17250,95730,332198,803007,1515096,5638455,765484

In [162]:
#add the rate column which is a fraction of the population
crimeData['Rate'] = crimeData['Total']/crimeData['Population']
#loop through all values in the other categories and make them into percentages
for i in range(2,len(crimeData.columns)-1):
    crimeData.iloc[:,i] = crimeData.iloc[:,i]/crimeData['Total']

In [163]:
#get the number of rows
numyears = len(crimeData['Rate'])
#get the average crime rate
avg = sum(crimeData['Rate'])/numyears
print("Average Crime Rate:",avg)
#get the median crime rate
med = np.median(crimeData['Rate']) 
#print results
if med > avg:
    print("Crime is usually lower than the median",med)
else:
    print("Crime is usually above the median which is",med)
lcc = {}
correls = []
#go throughout and find the least common crime and the correlation between each column
for header in crimeData.columns.values[2:]:
    lcc[header] = sum(crimeData[header])/numyears
    for n in crimeData.columns.values[2:]:
        if n == header:
            continue
        correls.append((header,n,crimeData[header].corr(crimeData[n])))
#print the results.
print("The least common crime is: ",min(lcc,key=lcc.get))
#Get the largest correllation & report
largestCorr = max(correls,key=lambda x:x[2])
print(largestCorr[0]+' and ' +largestCorr[1]+" are close in percentage, they have a correllation. It is "+str(largestCorr[2]))

Average Crime Rate: 0.04236939729496593
Crime is usually above the median which is 0.0415442385311
The least common crime is:  Murder
Violent and Aggravated Assault are close in percentage, they have a correllation. It is 0.962860547784

In [164]:
#argmax will give us the year of the most crimes
print("The majority of crimes hit an all-time high in the year: "+str(crimeData['Total'].idxmax()))
decadeSums = []
#sum up all of the total crimes over each decade
for i in range(0,60,10):
    decadeSums.append((i+1960,sum(crimeData.Total.iloc[i:i+10])))
#return the largest sum
worstDecade = max(decadeSums,key=lambda x:x[1])[0]    
print("{} had the greatest total amount of crime".format(worstDecade))
wdindex = worstDecade-1960
crimeSums = []
#sum up all of the crimes in each category in that decade
for i in crimeData.columns.values[2:]:
    crimeSums.append((i,sum(crimeData[i][wdindex:wdindex+10])))
#print results
worstCrime = max(crimeSums,key=lambda x:x[1])[0]
print("{} crimes were the commited the most in {}".format(worstCrime,worstDecade))

The majority of crimes hit an all-time high in the year: 1991
1990 had the greatest total amount of crime
Property crimes were the commited the most in 1990

In [165]:
#get the data where the property is < 90%
x1 = crimeData[crimeData['Property'] < 0.9 ]
#get the data where burglary is > 20%
x2 = crimeData['Burglary'] > 0.2
#get the data where the violent crime is > 20%
x3 = crimeData['Violent'] > 0.2
#condition on x2,x3 and get only the rate column
x1[x2 | x3]['Rate']

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

Year
1972    0.039614
1973    0.041544
1980    0.059500
1981    0.058582
1982    0.056037
1983    0.051750
1984    0.050313
1985    0.052071
1986    0.055019
1987    0.055756
1988    0.056642
1989    0.057410
1990    0.058203
1991    0.058978
1992    0.056602
1993    0.054844
2009    0.035058
2010    0.033504
2011    0.032924
2012    0.032558
Name: Rate, dtype: float64

In [166]:
#Import the data
driverData = pd.read_pickle("final_drivers.pickle")
carData = pd.read_pickle("final_accidents2.pickle")
#merge the 2 tables using an inner join keeping the listed columns
df1 = pd.merge(carData,driverData,on='ST_CASE')[['ST_CASE','AGE','DRINKING','DRUNK_DR','FATALS']]
df2 = pd.merge(carData,driverData,on='ST_CASE')[['ST_CASE','AGE','FATALS','SP','SPEEDREL']]

In [167]:
driverData.describe()

,ST_CASE,VEH_NO,AGE,DRINKING,SPEEDREL,YEAR
count,223490.000000,223490.000000,223490.000000,223490.000000,223490.000000,223490.000000
mean,280017.721375,1.442977,59.080854,2.815410,0.721903,2012.004170
std,162247.744491,1.339895,126.122369,3.841572,1.866967,1.411664
min,10001.000000,1.000000,3.000000,0.000000,0.000000,2010.000000
25%,122101.000000,1.000000,27.000000,0.000000,0.000000,2011.000000
50%,280215.000000,1.000000,41.000000,0.000000,0.000000,2012.000000
75%,420740.000000,2.000000,56.000000,8.000000,0.000000,2013.000000
max,560139.000000,90.000000,999.000000,9.000000,9.000000,2014.000000

In [168]:
#get the weather data
weatherdf = carData['WEATHER']
#define some dictionaries
weatherDict = {}
wdefDict = {0:'Unknown',1:'Clear',2:"Rain",3:'Sleet, Hail',4:'Snow',
            5:'Fog, Smog, Smoke',6:'Severe Crosswinds',7:'Blowing Sand, Soil, and Dirt',
            8:'Other',10:'Cloudy',11:'Blowing Snow',12:'Freezing Rain or Drizzle',
            98:'Not Reported',99:'Unknown'}
#go through all values and increment them to the dictionary
for x in weatherdf:
    x=str(x)
    if x in weatherDict:
        weatherDict[x]+=1
    else:
        weatherDict[x]=1
#print results
print("{} was the most common weather involved".format('\''+wdefDict[int(max(weatherDict,key=operator.itemgetter(0)))]+'\''))

'Not Reported' was the most common weather involved

In [169]:
spdf = carData[carData['SP']!=8]['SP']
print("Speeding got reported {} times".format(str(len(spdf))+'/'+str(len(carData['SP']))))

Speeding got reported 148206/148206 times

In [170]:
#get the data where the type of speeding is known
knownspdf = df2[df2['SPEEDREL']<9]['SPEEDREL']
spDefDict = {1:'Yes',0:'No',2:'Yes, Racing',3:'Yes, Exceeded Speed Limit',
            4:'Yes, Too Fast for Conditions',5:'Yes, Specifics Unknown',
            8:'No Driver Present/Unknown if Driver Present',
            9:'Unknown'}
spDict = {}
#loop through to see which one has the most occurences.
for x in knownspdf:
    x=str(x)
    if x in spDict:
        spDict[x]+=1
    else:
        spDict[x]=1
#print results
print("{} was the most common type of speeding".format('\''+spDefDict[int(max(spDict,key=operator.itemgetter(0)))]+'\''))

'Yes, Specifics Unknown' was the most common type of speeding

In [171]:
print("On average, {} drunk drivers are involved".format(df1['DRUNK_DR'].mean()*100//1))

On average, 31.0 drunk drivers are involved

In [172]:
#Define some dictionaries
monthdict = {}
monthDefDict = {1:'January',2:'February',3:'March',4:'April',
               5:'May',6:'June',7:'July',8:'August',9:'September',
               10:'October',11:'November',12:'December'}
#loop through to see which one has the most occurences.
for x in carData['MONTH']:
    x=str(x)
    if x in monthdict:
        monthdict[x]+=1
    else:
        monthdict[x]=1
#print results
print("{} has the most fatalities".format(monthDefDict[int(max(monthdict,key=operator.itemgetter(0)))]))

September has the most fatalities